default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Bubble_development
  username: phamdat
  password: ''
  port: 5433
  timeout: 5000

test:
  <<: *default
  database: Bubble_test
  username: phamdat
  password: ''
  port: 5433
  timeout: 5000

production:
  <<: *default
  database: Bubble_production
  username: phamdat
  password: ''
  port: 5432
  timeout: 5000